# Tensors
## Imports and Helpers

In [1]:
import tensorflow as tf

class col:
    header = '\033[95m' ; blue = '\033[94m' ; green = '\033[92m' ; reset = '\033[0m' ; bold = '\033[1m'

def header(string):
  print(f'{col.header}{string}{col.reset}\n')

def print_index_value(t, index):
  value =t[tuple(index)]
  print(f'{col.blue}t{index} =\n{col.green}{value} {col.reset}\n')


def info(t, indices):
  print(f'{col.blue}Tensor:{col.reset}\n{col.bold}{t.numpy()}{col.reset}\n\n{col.blue}rank =\t{col.green}{tf.rank(t)}{col.reset}\t{col.blue}\nshape =\t{col.green}{t.shape}{col.reset}')
  
  for index in indices:
    print_index_value(t, index)
  print()





## Points

In [2]:
header('Points are 0d tensors')
t = tf.Variable(2)
info(t,[[]])

t = tf.Variable(99)
info(t,[[]])

Points are 0d tensors

Tensor:
2

rank =	0	
shape =	()
t[] =
2 


Tensor:
99

rank =	0	
shape =	()
t[] =
99 




In [3]:
header('Vectors are 1d tensors')
t = tf.Variable([1])
t = tf.Variable([0, 1])
info(t, indices = [[1]])
t = tf.Variable([0, 1, 2, 3, 4, 5, 6 ,7])
info(t, indices = [[7]])


Vectors are 1d tensors

Tensor:
[0 1]

rank =	1	
shape =	(2,)
t[1] =
1 


Tensor:
[0 1 2 3 4 5 6 7]

rank =	1	
shape =	(8,)
t[7] =
7 




## Matrices

In [4]:
header('Matrices are 2d tensors.')
t = tf.Variable([[0], [10]])
info(t, indices = [[1], [1,0]])

t = tf.Variable([[1, 2], [10, 11]])
info(t, indices = [[1], [1,1]])

t = tf.Variable([[1, 2, 3, 4, 5], [10, 11, 12, 13 , 14], [20, 21, 22, 23 , 24],])
info(t, indices = [[2],[2,4]])

Matrices are 2d tensors.

Tensor:
[[ 0]
 [10]]

rank =	2	
shape =	(2, 1)
t[1] =
[10] 

t[1, 0] =
10 


Tensor:
[[ 1  2]
 [10 11]]

rank =	2	
shape =	(2, 2)
t[1] =
[10 11] 

t[1, 1] =
11 


Tensor:
[[ 1  2  3  4  5]
 [10 11 12 13 14]
 [20 21 22 23 24]]

rank =	2	
shape =	(3, 5)
t[2] =
[20 21 22 23 24] 

t[2, 4] =
24 




## General Tensors
They can be expressed in any number of dimensions like (0, 1, and 2) as in the above or more dimensions up to infinity.


In [5]:
header('Tensors come in any number dimensions')
t = tf.Variable([[[0], [10], [20]], [[100], [110], [120]]])
info(t, indices = [[1],[1,2],[1,2,0]])

t = tf.Variable([[[0,1,2], [10, 11, 12]], [[100, 101, 102], [110, 111, 112]]])
info(t, indices = [[0],[0,1], [1,0,1]])


t = tf.Variable([
    [[[0, 1, 2, 3], [10, 11, 12 , 13]], 
     [[100, 101, 102, 103], [110, 111, 112 , 113]],
     [[200, 201, 202, 203], [210, 211, 212 , 213]],
     ], 
     [[[1000, 1001, 1002, 1003], [1010, 1011, 1012 , 1013]], 
     [[1100, 1101, 1102, 1103], [1110, 1111, 1112 , 1113]],
     [[1200, 1201, 1202, 1203], [1210, 1211, 1212 , 1213]],]
                                                 ])
info(t, indices = [[1], [1,2], [1,2,1], [1,2,1,3]])

Tensors come in any number dimensions

Tensor:
[[[  0]
  [ 10]
  [ 20]]

 [[100]
  [110]
  [120]]]

rank =	3	
shape =	(2, 3, 1)
t[1] =
[[100]
 [110]
 [120]] 

t[1, 2] =
[120] 

t[1, 2, 0] =
120 


Tensor:
[[[  0   1   2]
  [ 10  11  12]]

 [[100 101 102]
  [110 111 112]]]

rank =	3	
shape =	(2, 2, 3)
t[0] =
[[ 0  1  2]
 [10 11 12]] 

t[0, 1] =
[10 11 12] 

t[1, 0, 1] =
101 


Tensor:
[[[[   0    1    2    3]
   [  10   11   12   13]]

  [[ 100  101  102  103]
   [ 110  111  112  113]]

  [[ 200  201  202  203]
   [ 210  211  212  213]]]


 [[[1000 1001 1002 1003]
   [1010 1011 1012 1013]]

  [[1100 1101 1102 1103]
   [1110 1111 1112 1113]]

  [[1200 1201 1202 1203]
   [1210 1211 1212 1213]]]]

rank =	4	
shape =	(2, 3, 2, 4)
t[1] =
[[[1000 1001 1002 1003]
  [1010 1011 1012 1013]]

 [[1100 1101 1102 1103]
  [1110 1111 1112 1113]]

 [[1200 1201 1202 1203]
  [1210 1211 1212 1213]]] 

t[1, 2] =
[[1200 1201 1202 1203]
 [1210 1211 1212 1213]] 

t[1, 2, 1] =
[1210 1211 1212 1213] 

t[1, 2, 1, 